<!-- <div class="container-fluid bar-segment" id="stats" style="background:black;">
  <h1>Branded video is the future</h1>
  
</div> -->
<div class="next">	
	<div class="container first-block">
		<h1>Experience Imagin&middot;ere 4K Video Solutions</h1>
		<p>
		  	A Brand has only a Few Seconds to Capture an Audience. 4K Video is the Future for Evoking an Experience.
    	</p>
    	<div class="row hidden-sm hidden-md hidden-lg">
	      <div class="col-xs-4">
	        <div class="first-circle"></div>
	        <p><b>74%</b> of all Internet Traffic will be generated by Video in 2017.</p>
	      </div>
	      <div class="col-xs-4">
	        <div class="third-circle"></div>
	        <p><b>68%</b> of people share Videos that they watch on their Smartphones.</p>
	      </div>
	      <div class="col-xs-4" id="times">
	        <div class="second-circle"></div>
	        <p>Including Video on a landing page increases conversion rates by <b>80%.</b></p>
	      </div>
	  </div>
	  <div class="hidden-xs container stats-wrap">
		<table>
		  <tr>
		    <td class="col-xs-4"><div class="first-circle"></div></td>
		    <td class="col-xs-4"><div class="third-circle"></div></td>
		    <td class="col-xs-4"><div class="second-circle"></div></td>
		  </tr>
		  <tr>
			<td class="col-xs-4"><p><b>74%</b> of all Internet Traffic will be generated by Video in 2017.</p></td>
			<td class="col-xs-4"><p><b>68%</b> of people share Videos that they watch on their Smartphones.</p></td>
		    <td class="col-xs-4"><p>Including Video on a landing page increases conversion rates by <b>80%.</b></p></td>
		  </tr>
    </table>
	</div>
	<div class="four-k-button">
		<a href="/corporate-reel">
			<img src="/img/4k-Video-Button.png"/>
		</a>
	</div>
	<div id="ticker">
		<ul id="webTicker">
			<li>Telus now distributes 4K Video in Canada. Find more information on <a href="http://www.telus.com/en/bc/tv/new/optik-4k">Telus.com</a><!--  <span class="dot-sep">&middot;</span>&nbsp; --></li>
		</ul>
	</div>
	  <!-- <a href="#specialties">
	  	<i class="fa fa-chevron-down" aria-hidden="true" class="arrow-down" id="down-video"></i>
	  </a> -->
	</div>
	<div class="container-fluid first-fluid bar-segment" id="specialties">
		<div class="container">
			<h2>Cinematic Branded Video Solutions to Evoke an Experience</h2>
			<h3>OUR PROCESSES:</h3>
			<div class="split-menu">
				<ul class="split-ul">
					<li data-title="Work with our team to develop the experience you want to evoke in your customer’s base."><img src="/img/split-menu/creative.png"> CREATIVE</li>
					<li data-title="Using Scripts &amp; Storyboarding we develop and refine the experience."><img src="/img/split-menu/pre-production.png"> PRE-PRODUCTION</li>
					<li data-title="Professional Lighting and Staging by the best in the industry to create the scene."><img src="/img/split-menu/staging.png"> STAGING</li>
				</ul>
				<ul class="split-ul">
					<li data-title="4K Video High-Speed Camera offering that shoots an incredible 1000 frames per second or our Movie Industry Standard Cinematic 6K Camera."><img src="/img/split-menu/video.png"> VIDEO PRODUCTION</li>
					<li data-title="Video Editing, Color Correction, Sound and Music Development, 7.1 Surround Sound and Animation."><img src="/img/split-menu/post-production.png"> POST-PRODUCTION</li>
					<li data-title="Search Engine Optimization, Launch Planning, and Media Buying give us the opportunity to boost a Brand exponentially."><img src="/img/split-menu/marketing.png"> ADVERTISING</li>
				</ul>
			</div>
			<div class="split-menu-mobile">
				<ul class="split-ul-mobile">
					<li>CREATIVE <img src="/img/split-menu/creative.png"></li>
					<li>PRE-PRODUCTION <img src="/img/split-menu/pre-production.png"></li>
					<li>STAGING <img src="/img/split-menu/staging.png"></li>
					<li><img src="/img/split-menu/video.png"> VIDEO PRODUCTION</li>
					<li><img src="/img/split-menu/post-production.png"> POST-PRODUCTION</li>
					<li><img src="/img/split-menu/marketing.png"> ADVERTISING</li>
				</ul>
			</div>
			<!-- <ul>
				<li><b>Creative Briefing</b> - Work with our team to develop the experience you want to evoke in your customer’s base.</li><br/>
				<li><b>Pre-Production</b> - Using Scripts &amp; Storyboarding we develop and refine the experience.</li><br/>
				<li><b>Staging</b> - Professional Lighting and Staging by the best in the industry to create the scene. </li><br/>
				<li><b>Video Production</b> - 4K Video High-Speed Camera offering that shoots an incredible 1000 frames per second or our Movie Industry Standard Cinematic 6K Camera.</li><br/>
				<li><b>Post Production</b> Video Editing, Color Correction, Sound and Music Development, 7.1 Surround Sound and Animation.</li><br/>
			</ul> -->
			<div class="col-xs-12 center-block dbl-button">
			  <!-- <div class="col-xs-12 col-sm-6">
			  <a href="#segment-bar" class="link-hs-button col-xs-12">
			  <div class="high-speed-btn first-dbl-btn">
			    Learn More about the Technology <i class="fa fa-angle-right" aria-hidden="true"></i>
			  </div>
			  </a>
			  </div> -->
			  <div class="col-xs-12 col-sm-6 center-block" style="float:none;padding-left:0;padding-right:0;">
				  <a href="/our-services" class="link-hs-button col-xs-12">
				  <div class="high-speed-btn last-dbl-btn">
				    Learn More about our Services <i class="fa fa-angle-right" aria-hidden="true"></i>
				  </div>
			  	  </a>
		  	  </div>
			</div>
		</div>
	</div>
   <div class="services">
  </div>
	<div class="c-btn-wrapper">
	  <h5>Want to learn more?</h5>
	  <a href="/our-company#contact-us-now">
	  <div class="contact-button">
	    Create your Branded Video Now <i class="fa fa-angle-right" aria-hidden="true"></i>
	  </div>
	  </a>
	</div>
</div>